### ISSUE TITLE
How can we customize the load widget?

### ISSUE THREAD

**Issue by techttiru** [kodal/load_future#1]
Hi,
Thanks for sharing this package information in future_progress dialog package. I have been using this future progress dialog package and i see some issues in it. so i want to use to your package. i tried and its working fine but before i started to use, is there a way customize the widget? for ex: this load widget shows "blue" color circular dialog but i would like to show something similar to what was being shown in future progress dialog like, showing progress on top of small white background container. Also, i want to pass some custom message to the widget when its showing like "Loading..". can we do it?

Appreciate your response!.

**Comment by kodal** [comment]
Hello, yes, you can customize when configure:
```
LoadWidget(
   navigatorKey: navigatorKey,
   indicator: CustomWidget(),
)
```
